# -*- encoding: utf-8 -*-

shipped_order = {
    'AmazonOrderId': {'value': '112-7448244-2268261'},
    'OrderStatus': {'value': 'Shipped'},
    'PaymentMethodDetails': {'PaymentMethodDetail': {'value': 'Standard'}, 'value': '\n          '},
    'LatestDeliveryDate': {'value': '2018-03-13T06:59:59Z'},
    'LatestShipDate': {'value': '2018-01-31T07:59:59Z'},
    'EarliestShipDate': {'value': '2018-01-29T08:00:00Z'},
    'IsPremiumOrder': {'value': 'false'},
    'IsBusinessOrder': {'value': 'false'},
    'ShippedByAmazonTFM': {'value': 'false'},
    'PurchaseDate': {'value': '2018-01-28T07:07:21Z'},
    'ShipmentServiceLevelCategory': {'value': 'Standard'},
    'OrderTotal': {'CurrencyCode': {'value': 'USD'}, 'Amount': {'value': '7.93'}, 'value': '\n          '},
    'FulfillmentChannel': {'value': 'MFN'},
    'NumberOfItemsUnshipped': {'value': '0'},
    'IsReplacementOrder': {'value': 'false'},
    'ShippingAddress': {
        'City': {'value': 'ENGLEWOOD'},
        'AddressType': {'value': 'Residential'},
        'Name': {'value': 'David K. Horton'},
        'CountryCode': {'value': 'US'},
        'value': '\n          ',
        'Phone': {'value': '9377653592'},
        'StateOrRegion': {'value': 'OH'},
        'AddressLine1': {'value': '711 W WENGER RD APT 136'},
        'PostalCode': {'value': '45322-1909'}},
    'OrderType': {'value': 'StandardOrder'},
    'LastUpdateDate': {'value': '2018-01-30T01:31:28Z'},
    'EarliestDeliveryDate': {'value': '2018-02-16T08:00:00Z'},
    'PaymentMethod': {'value': 'Other'},
    'SalesChannel': {'value': 'Amazon.com'},
    'BuyerEmail': {'value': 'lbbwlycljybbzlj@marketplace.amazon.com'}, 'value': '\n        ',
    'ShipServiceLevel': {'value': 'Std US D2D Dom'},
    'BuyerName': {'value': 'Azad'},
    'NumberOfItemsShipped': {'value': '1'},
    'IsPrime': {'value': 'false'},
    'MarketplaceId': {'value': 'ATVPDKIKX0DER'}
}