# -*- coding: utf-8 -*-

from . import product_template
from . import product_product
from . import amazon_product_ept
from . import amazon_sale_order_ept
from . import sale_order_line
from . import amazon_sale_order_line_ept
from . import amazon_process_log_book
from . import amazon_transaction_log
from . import active_product_listing_report_ept
from . import down_sync_product_line
from . import amazon_instance_ept
from . import amazon_seller_ept
from . import product_brand
from . import b2b_shop_collect_convert
from . import amazon_browse_node_ept
from . import sync_browse_node
from . import feed_submission_history
from . import res_partner
from . import product_image
from . import ir_sequence
from . import b2b_distributor_amazon_template
from . import amazon_attribute_ept
from . import product_attribute
from . import get_product_info
from . import sale_order
from . import amazon_category_ept
from . import stock_picking
from . import account_journal